version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Authenticate with GHCR
          command: |
            echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            docker build -t ghcr.io/$GHCR_USERNAME/karsajobs:latest .
            docker push ghcr.io/$GHCR_USERNAME/karsajobs:latest

workflows:
  version: 2
  lint-test-build:
    jobs:
      - lint-dockerfile
      - test-app:
          requires:
            - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - test-app